projects/urls.py
from django.urls import path
from projects.views import ProjectListView, ProjectView, CreateProject

urlpatterns = [
    path("", ProjectListView, name="list_projects"),
    path("<int:id>/", ProjectView, name="show_project"),
    path("create/", CreateProject, name="create_project"),
]

tasks/urls.py
from django.urls import path
from tasks.views import CreateTask, TaskListView

urlpatterns = [
    path("create/", CreateTask, name="create_task"),
    path("mine/", TaskListView, name="show_my_tasks"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from projects.views import ProjectListView


def redirect_to_projects(request):
    return redirect(ProjectListView)


urlpatterns = [
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    path("", redirect_to_projects, name="home"),
    path("accounts/", include("accounts.urls")),
    path("tasks/", include("tasks.urls")),
    path("companies/", include("companies.urls")),
]

companies/models.py
from django.db import models


# Create your models here.
class Company(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()

    def __str__(self):
        return self.name

projects/models.py
from django.db import models
from django.contrib.auth.models import User


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    owner = models.ForeignKey(
        User,
        related_name="projects",
        on_delete=models.CASCADE,
        null=True,
    )

    def __str__(self):
        return self.name

projects/forms.py
from django.forms import ModelForm
from projects.models import Project


class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = [
            "name",
            "description",
            "owner",
        ]

projects/views.py
from django.shortcuts import render, get_object_or_404, redirect
from projects.models import Project
from django.contrib.auth.decorators import login_required
from projects.forms import ProjectForm


@login_required
def ProjectListView(request):
    projects = Project.objects.filter(owner=request.user)
    context = {
        "projects": projects,
    }
    return render(request, "projects/projects.html", context)


@login_required
def ProjectView(request, id):
    project = get_object_or_404(Project, id=id)
    context = {
        "project": project,
    }
    return render(request, "projects/project.html", context)


@login_required
def CreateProject(request):
    if request.method == "POST":
        form = ProjectForm(request.POST)
        if form.is_valid():
            project = form.save(False)
            project.save()

        return redirect(ProjectListView)

    else:
        form = ProjectForm()
    context = {
        "form": form,
    }
    return render(request, "projects/create.html", context)


# Create your views here.

projects/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>
            {% block title %}
            {% endblock title %}
        </title>
        <link rel="stylesheet" href="{% static 'css/styling.css' %}">
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <a href={% url "show_my_tasks" %}>My tasks</a>
                        </li>
                        <li>
                            <a href={% url "list_projects" %}>My projects</a>
                        </li>
                        <li>
                            <a href={% url "company_list" %}>Companies</a>
                        </li>
                        <li>
                            <a href={% url "logout" %}>Logout</a>
                        </li>
                    {% endif %}
                    {% if not user.is_authenticated %}
                        <li>
                            <a href={% url "login" %}>Login</a>
                        </li>
                        <li>
                            <a href={% url "signup" %}>Signup</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        {% block content %}
        {% endblock content %}
    </body>
</html>